version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    command: rails db:migrate
    # ports:
    #   - "5432:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
      - redis

  redis:
    image: redis:3.0.6
    command: redis-server
    # ports: 
    #   - 6379:6379
    
  sidekiq:
    build: .
    volumes:
      - /home/steffan/Documents/PUC/Sem10/Proyecto de Especialidad/probando cosas/my docker apiSIV/apiSIV/cotizaC.mdb:/myapp/cotizaC.mdb 
      - .:/myapp
    depends_on:
      - db
      - redis
    env_file:
      - .env
    # networks:
    #   - dockernet
    command: bundle exec sidekiq -C config/sidekiq.yml

# networks:
#   dockernet:
#     external: true
