version: '2'

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

    # ports:
    #   - "5433:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
      - redis
    links:
      - postgres
      - sidekiq
    # environment:
    #   - RAILS_ENV=production

  redis:
    image: redis:3.0.6
    command: redis-server
    # ports:
    #   - 6379:6379

  sidekiq:
    build: .
    volumes:
      - /home/osboxes/Desktop/Nuevo Git/apiSIV/cotizaC.mdb:/myapp/cotizaC.mdb
      - .:/myapp
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    # networks:
    #   - dockernet
    command: bundle exec sidekiq -C config/sidekiq.yml

# networks:
#   dockernet:
#     external: true

volumes:
  pgdata: {}
